version: "3.1"

services:
  db:
    build: .
    container_name: apiprisma-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devtraining

  dbtest:
    build: .
    container_name: apiprisma-test-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apiprisma
